version: '3.4'

services:
  facebluring:
    image: facebluring
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 auto_blur_image.py "]
    ports:
      - 5678:5678
